### ISSUE TITLE
Documentação do Horse

### ISSUE THREAD

**Issue by chambber** [HashLoad/horse-doc#1]
_(primeiramente desculpas, sei que o repositório está todo em Inglês, e estou escrevendo em Português)_

Gostaria de parabenizar que esse projeto é fantástico, principalmente pela facilidade e simplicidade a que ele se propõe que me remete a algumas ferramentas em NodeJs que sinto falta em Delphi/Pascal, principalmente na área Web!

Agora, queria saber como eu poderia ajudar, não sou expert, mas tenho alguma experiência em Delphi, e nem que seja para criar uma documentação, uma home page. O que quero saber é, posso ajudá-los, e se sim, no quê?

**Comment by chambber** [comment]
Sobre o andamento da tarefa:
  - Implementei suporte a vários idiomas na documentação,
  - Configurei a integração com o [Netlify](https://www.netlify.com) com redirecionamento de idioma e desenvolvimento contínuo no *master*.
Nessa semana estarei finalizando a documentação seguindo os assuntos mencionados.

Quanto a documentação em inglês não tenho conhecimento suficiente para escrevê-la, mas estou preparando os arquivos para ficar fácil de serem traduzidos, tudo bem?

A documentação está usando um [domínio gratuito](https://horse.netlify.com) por enquanto, não sei como pretendem fazer em relação a domínio.

**Comment by hunsche** [comment]
Muito bom,

A integração com o [Netlify](https://www.netlify.com/) vai facilitar muito nossa vida em relação aos deploys e contribuições.

Referente a documentação em inglês, aconselho deixar tudo traduzido automaticamente pelo google translate, logo depois podemos ir ajustando a mesma para fazer mais sentido.

Hoje possuimos o dominio [hashload.com](https://hashload.com), é possivel criarmos o dominio [horse.hashload.com](https://horse.hashload.com).

**Comment by chambber** [comment]
Certo, deixarei com tradução automática.

Sobre o domínio, tudo bem, estarei alterando para [horse.hashload.com](horse.hashload.com).

**Comment by hunsche** [comment]
Referente ao domínio, como posso configurar o apontamento?

**Comment by chambber** [comment]
A configuração de DNS seria as seguintes:
 - dns1.p06.nsone.net
 - dns2.p06.nsone.net
 - dns3.p06.nsone.net
 - dns4.p06.nsone.net

**Comment by hunsche** [comment]
[DNS](http://horse.hashload.com) apontado.

**Comment by hunsche** [comment]
Boa tarde,
@chambber eu criei uma [issue](https://github.com/HashLoad/horse/issues/6), para referenciar a documentação ao projeto principal, pois não tive tempo para fazer o mesmo.

Caso tenha disponibilidade, pensei em refazermos o README.MD para algo mais intuitivo e com mais informações.

**Comment by chambber** [comment]
Boa noite,
Semana corrida, não consegui te responder, desculpe-me.

Quanto a documentação estou escrevendo e também criando uma API de todos os métodos disponíveis.
Atualmente criei algumas aplicações para testar as funcionalidades para poder entender melhor e escrever sobre e queria confirmar algumas coisas:
 - Os parâmetros não fazem validações de expressões regulares?
 - Quando eu não quiser a continuação do próximo *Callback*, devo lançar uma exceção como por exemplo, `EHorseCallbackInterrupted`?

Quanto ao README tinha pensado sim, e posso sim.

**Comment by hunsche** [comment]
Bom dia, fica tranquilo sabemos bem como é ter a semana corrida 😉

Muito boa a ídeia de explorar a API exemplificando os métodos.

Referente às perguntas:

- _Os parâmetros não fazem validações de expressões regulares?_ **Atualmente não faz validação por regex, mas é uma excelente feature, podemos colocar no roadmap do horse, ainda em construção.**

- _Quando eu não quiser a continuação do próximo Callback, devo lançar uma exceção como por exemplo, EHorseCallbackInterrupted?_ **Sim, hoje a parada do callback é forçada por esta exception.**
